export const articleBodies:Record<string,{title:string;dek:string;published:string;sections:{heading:string;body:string[]}[]}>= {
"website-redesign-business-case":{title:"How to build a business case for a website redesign",dek:"Separate surface-level dissatisfaction from the customer, commercial and operational problems a new site must solve.",published:"11 July 2026",sections:[
{heading:"Start with the cost of the current situation",body:["“The site looks old” may be true, but it is not yet an investment case. Find the consequence. Are suitable buyers failing to understand the offer? Is the sales team rewriting the same explanation in every proposal? Can nobody publish an important update without a developer? Is organic demand landing on pages that do not answer the question?","Describe the current journey with evidence you can obtain: enquiries by source and quality, conversion at important steps, common sales objections, search impressions, content maintenance time, accessibility problems and support questions. A small, credible baseline is more useful than an impressive invented forecast."]},
{heading:"Choose the problem class",body:["A visual refresh changes expression. A repositioning changes what the company says and to whom. A journey redesign changes how visitors understand, compare and act. A platform change addresses publishing, integration, reliability or ownership. Many failed redesigns buy the first while expecting all four.","Write one sentence for the primary change: ‘After launch, operations leaders should be able to recognise their use case, understand our approach and start a qualified conversation without needing a referral.’ That statement gives content, design and measurement a common job."]},
{heading:"Define evidence, not guaranteed uplift",body:["A new website cannot guarantee revenue. It can create measurable leading conditions: more qualified visitors reaching decision content, better completion of a key form, fewer avoidable questions, faster publishing and improved search coverage. Set a baseline, a target range and a review date.","Include the cost of doing nothing and the cost of delay, but do not manufacture urgency. If the existing site creates no material constraint, a targeted content or performance intervention may be the better recommendation."]},
{heading:"Scope a complete first release",body:["Prioritise the pages and capabilities needed for the primary journey, plus the foundations every production site requires: accessibility, privacy, security, metadata, error handling, analytics decisions and maintainable ownership. Avoid calling these non-functional extras; they determine whether the site can be trusted.","A useful business case finishes with a decision: retain and improve, redesign the experience, rebuild the platform, or stop. The strongest partner should be willing to recommend the smallest route that addresses the evidence."]}]},
"ai-automation-opportunity-scorecard":{title:"Which workflow should you automate first?",dek:"A useful first automation is frequent enough to matter, bounded enough to observe and safe enough to learn from.",published:"11 July 2026",sections:[
{heading:"Do not start with the loudest annoyance",body:["Teams naturally nominate the task they dislike most. Frustration matters, but it does not establish value or feasibility. Map a real workflow from trigger to outcome, including exceptions, approvals, workarounds and the systems people use outside the official process.","Score candidates from one to five across frequency, time per occurrence, error rate, customer consequence, data availability, rule stability and reversibility. Record confidence beside every score. A confident medium-value candidate is often a better pilot than an exciting use case built on guesses."]},
{heading:"Account for failure cost",body:["Automation changes the speed and scale of mistakes. A workflow that drafts an internal summary has a different risk profile from one that sends regulated advice or alters a customer account. Identify who notices a failure, how it is reversed and what evidence must be retained.","Use human review deliberately. It is not a temporary embarrassment: approval can be the correct permanent design where judgement, accountability or rare exceptions matter. The goal is to remove repeat work without pretending uncertainty has disappeared."]},
{heading:"Measure the whole system",body:["Time saved is useful but incomplete. Track correction effort, exception volume, completion time, quality and user trust. Include model, platform, monitoring and maintenance costs. An AI step that is cheap per request may still be expensive to evaluate and supervise.","Define a pilot threshold before building: for example, reduce median handling time while keeping correction rates below an agreed level across a representative set of cases. If the threshold is not met, the result is evidence—not a reason to move the goalposts."]},
{heading:"Pick a bounded first move",body:["A good pilot has a clear start, end, owner and fallback. It runs beside the existing process long enough to compare results. It produces logs that explain what happened without collecting unnecessary personal data.","The final decision should be build, buy, integrate, redesign the process without AI, or stop. Automation discovery earns its cost when it makes any of those conclusions defensible."]}]},
"mvp-scope-without-regret":{title:"How to scope an MVP without creating a disposable product",dek:"Minimum viable should describe the smallest complete learning system, not the cheapest pile of screens.",published:"11 July 2026",sections:[
{heading:"Protect the complete journey",body:["An MVP needs fewer use cases, not half a use case. A customer must still understand the promise, enter the journey, receive the core value, recover from ordinary failure and know what happens next. Removing error states, accessibility or operational ownership does not test the proposition; it changes the conditions of the test.","Write the single behaviour the release must enable and the evidence that would change the next decision. Every feature should either enable that behaviour, reduce a material risk or collect the required evidence."]},
{heading:"Find the irreversible choices",body:["Some shortcuts are cheap to replace; others become the foundation. Identity, data ownership, permissions, audit needs, payment flows and integration boundaries deserve early attention. Typography polish or an advanced preference panel rarely does.","Document which parts are production foundations, which are deliberate temporary constraints and which are manual behind the scenes. A manual operation can be excellent product discovery when users still receive a coherent and honest service."]},
{heading:"Scope by uncertainty",body:["If customer desirability is uncertain, prototype the journey before engineering the platform. If technical feasibility is uncertain, isolate the integration or model behaviour. If operational viability is uncertain, run the service manually with real cases. One large build is an expensive way to answer three different questions.","Use acceptance criteria that describe observable behaviour. ‘User can resume a failed upload without losing completed work’ is testable. ‘Robust upload experience’ is not."]},
{heading:"Plan the next decision, not the fantasy roadmap",body:["A roadmap after the MVP should be conditional: if activation is strong but retention is weak, investigate repeat value; if people abandon onboarding, inspect expectation and friction; if the operational load is excessive, improve tooling before acquisition.","The release is viable when it creates value safely enough to learn from real use. It is successful when that learning makes the next investment clearer."]}]},
"website-project-costs":{title:"What determines the cost of a professional website?",dek:"Price follows uncertainty, content depth, design ambition, integration risk and the level of assurance the launch requires.",published:"11 July 2026",sections:[
{heading:"The number of pages is a weak starting point",body:["Ten pages assembled from one template may be simpler than a single eligibility journey with conditional content, validation and integration. Useful estimates consider page types, decision complexity, content readiness, component variety, data sources, languages and the cost of failure.","Ask what the price includes across discovery, copy, design, development, content migration, accessibility, analytics, search foundations, browser testing, training, deployment and post-launch support. A smaller quote often reflects a different boundary rather than greater efficiency."]},
{heading:"Content is product work",body:["A website cannot explain an unclear proposition through styling. Interviews, message development, evidence gathering, information architecture and editing require time. If the organisation supplies copy, allow for structure, quality control, metadata and migration rather than assuming it arrives production-ready.","New companies should invest in clear mechanisms and process rather than synthetic trust. Honest pricing guidance, useful explanations and specific fit criteria can do more than generic claims."]},
{heading:"Custom design should buy distinction or clarity",body:["A robust template can be the right answer for a straightforward local service. Custom design earns its cost when brand expression, complex content, accessibility or interaction creates a meaningful commercial difference. Bespoke should not mean every component behaves differently.","Performance and accessibility are easiest to achieve when treated as design constraints from the beginning. Retrofitting them after approval usually costs more and produces compromises."]},
{heading:"Compare proposals by risk ownership",body:["Look for assumptions, exclusions, acceptance criteria, payment stages, change handling and launch responsibility. Ask who owns integration testing and what happens when third-party access arrives late. Check whether source code, design assets and documentation are handed over.","A credible supplier can explain the starting range, the variables that move it and which discovery would reduce uncertainty. Precision before evidence is not transparency; it is theatre."]}]},
"ai-prototype-production-gap":{title:"Why useful AI prototypes fail on the way to production",dek:"A convincing demonstration answers ‘can it work once?’ Production must answer ‘how does it behave repeatedly, safely and economically?’",published:"11 July 2026",sections:[
{heading:"The prototype hides the distribution",body:["A demonstration usually contains cooperative inputs selected by its maker. Real work contains missing context, unusual formats, conflicting instructions, malicious content and cases nobody remembered to mention. Build an evaluation set from representative and difficult examples before tuning prompts around memorable failures.","Define useful quality dimensions separately: factual correctness, completeness, format compliance, appropriate refusal, tone and latency. A single pass rate can conceal a dangerous weakness."]},
{heading:"Reliability is a system property",body:["Models sit inside products. Retrieval quality, permissions, tool behaviour, timeouts, retries, version changes and user expectations all affect the result. Store enough structured evidence to investigate failures while minimising personal data and respecting retention requirements.","Design explicit fallbacks. The product should explain when it cannot complete a task, preserve the user’s work and provide a safe route forward. Silent invention is not a graceful degradation strategy."]},
{heading:"Operating cost includes attention",body:["Token cost is only one line. Add evaluation, observability, incident handling, vendor review, human approval and the cost of correcting output. Measure cost per successfully completed outcome, not cost per model request.","Latency also changes behaviour. A slower, more capable model may reduce completion because users abandon it. A faster model with targeted tools and validation can create the better product."]},
{heading:"Production begins with ownership",body:["Name the person accountable for quality thresholds, data decisions, provider changes and incidents. Define what triggers a rollback and how people perform the task when the AI path is unavailable.","A prototype should therefore test the operating model as well as the output. The honest conclusion may be to narrow the use case, keep permanent review, use conventional automation, buy an existing tool or stop. That is successful discovery."]}]}
};
