"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
type Answers={org:string;challenge:string;friction:string;budget:string;timeline:string};
const initial:Answers={org:"",challenge:"",friction:"",budget:"",timeline:""};
const questions=[
 {key:"org",title:"What kind of organisation is this for?",options:[["small","Small business"],["startup","Startup or new venture"],["established","Established organisation"],["team","Internal team"]]},
 {key:"challenge",title:"What needs to change most?",options:[["explain","We need to explain and convert better"],["workflow","A workflow is too manual"],["product","We need to test or build a product"],["ai","We need a sensible AI direction"]]},
 {key:"friction",title:"Where is the strongest friction?",options:[["customers","Customer acquisition or service"],["operations","Internal operations"],["data","Information and data flow"],["decision","Uncertainty about what to build"]]},
 {key:"budget",title:"What investment range is realistic?",options:[["explore","Still exploring"],["small","Under £5,000"],["medium","£5,000–£20,000"],["large","£20,000+"]]},
 {key:"timeline",title:"When would progress be useful?",options:[["soon","Within 1–2 months"],["quarter","This quarter"],["later","Later this year"],["open","No fixed date"]]}
] as const;
export function OpportunityMapper(){const [step,setStep]=useState(0);const [answers,setAnswers]=useState<Answers>(initial);const complete=step===questions.length;const result=useMemo(()=>{if(!complete)return null;const c=answers.challenge;const title=c==="explain"?"Website clarity and conversion sprint":c==="workflow"?"Workflow mapping and automation pilot":c==="product"?"Product discovery and prototype sprint":"AI opportunity mapping sprint";const first=c==="explain"?"Audit the proposition, priority journeys, content gaps and measurement.":c==="workflow"?"Observe the real workflow and quantify volume, exceptions and failure cost.":c==="product"?"Define the user, core job and riskiest assumption before choosing features.":"Rank candidate use cases by value, feasibility, data readiness and consequence of error.";return{title,steps:[first,"Create one testable model of the improved journey.","Use evidence from the test to decide whether to build, buy, integrate or stop."],caution:answers.budget==="small"?"Keep the first engagement tightly bounded. Prioritise a decision or pilot, not a compressed full build.":"Confirm scope, operating ownership and measurable acceptance criteria before implementation."}},[complete,answers]);function choose(key:keyof Answers,value:string){setAnswers(a=>({...a,[key]:value}));setStep(s=>s+1)}function reset(){setAnswers(initial);setStep(0)}return <><section className="page-intro shell"><p className="kicker">Free tool · no email gate</p><h1>Map the opportunity.</h1><p className="lede">Five decisions. A useful first-pass route. This is planning guidance, not a quotation or a substitute for discovery.</p></section><section className="section shell mapper-tool"><div className="mapper-progress"><span>Digital Opportunity Mapper</span><span>{complete?"Roadmap":`Question ${step+1} of ${questions.length}`}</span><progress max={questions.length} value={step} aria-label={`${step} of ${questions.length} questions complete`}/></div>{!complete? <div className="question"><p className="kicker">Choose the closest answer</p><h2>{questions[step].title}</h2><div className="option-grid">{questions[step].options.map(([value,label])=><button key={value} onClick={()=>choose(questions[step].key,value)}><span>{label}</span><b aria-hidden="true">→</b></button>)}</div>{step>0&&<button className="back-button" onClick={()=>setStep(s=>s-1)}>← Back</button>}</div>:result&&<div className="roadmap" aria-live="polite"><p className="kicker">Suggested starting route</p><h2>{result.title}</h2><ol>{result.steps.map((x,i)=><li key={x}><span>0{i+1}</span><p>{x}</p></li>)}</ol><aside><b>Keep in view</b><p>{result.caution}</p></aside><div className="actions"><Link className="button" href={`/contact?route=${encodeURIComponent(result.title)}`}>Discuss this route <span>→</span></Link><button className="button secondary" onClick={reset}>Start again</button></div></div>}</section></>}
